baseURL = "http://pixxstudios.com/"
languageCode = "en-us"
title = "Gagandeep Singh"
theme = "tale"

[params]
    desciption = "Gagandeep's blog"
    mainSection = "posts"
    showAllPostsOnHomePage = false
    showProjectsList = false

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1